MyFirstASPAPP/Models/Biere.cs
using MyFirstASPAPP.Validators;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyFirstASPAPP.Models
{
    public class Biere
    {
        public int Id { get; set; }

        [Required]
        [MinLength(2)]
        [MaxLength(50)]
        public string Nom { get; set; }

        [Range(1,10000)]
        public decimal Prix { get; set; }

        public string Image { get; set; }
    }
}

MyFirstASPAPP/Models/Personne.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyFirstASPAPP.Models
{
    public class Personne
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int Age { get; set; }
    }
}

MyFirstASPAPP/Models/Reservation.cs
using MyFirstASPAPP.Validators;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyFirstASPAPP.Models
{
    public class Reservation
    {
        [Required]
        [MinLength(2, ErrorMessage = "Mon Message Custom")]
        [MaxLength(50)]
        public string NomClient { get; set; }
        
        [Required]
        [EmailAddress]
        [MaxLength(255)]
        public string EmailClient { get; set; }
        
        [Required]
        [Range(1, 50)]
        public int NbPersonnes { get; set; }
        
        [Required]
        [MaxLength(1000)]
        public string Message { get; set; }
        
        [Required]
        [NotBeforeToday]
        public DateTime Date { get; set; }

        [Required]
        [BetweenHours]
        public DateTime Time { get; set; }
    }
}

MyFirstASPAPP/Controllers/BiereController.cs
using MyFirstASPAPP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFirstASPAPP.Controllers
{
    public class BiereController : Controller
    {
        private static List<Biere> bieres = new List<Biere>
        {
            new Biere { Id = 1, Nom = "Orval", Image = "/Content/Images/orval.jpg", Prix = 3 },
            new Biere { Id = 2, Nom = "Jup", Image = "/Content/Images/jup.jpg", Prix = 2 },
            new Biere { Id = 3, Nom = "Cuvée de Trolls", Image = "/Content/Images/cuvee.png", Prix = 2.5m },
        };

        public ActionResult Index()
        {
            return View(bieres);
        }

        public ActionResult Details(int id)
        {
            Biere model = bieres.FirstOrDefault(b => b.Id == id);
            if (model == null) return new HttpNotFoundResult();
            return View(model);
        }

        // affichage du formulaire
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        //traitement du formulaire
        [HttpPost]
        public ActionResult Add(Biere model)
        {
            if (ModelState.IsValid)
            {
                // Ajouter dans la liste statique
                // Plus tard on enregistrera dans la db
                model.Id = bieres.Count + 1;
                bieres.Add(model);
                return RedirectToAction("Index");
            }
            else
            {
                // afficher  un message d'erreur
                return View(model);
            }
            
        }
    }
}

MyFirstASPAPP/Controllers/DefaultController.cs
//using MyFirstASPAPP.Models;
using MyFirstASPAPP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFirstASPAPP.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewWithVariable()
        {
            return View(42);
        }

        public static List<Personne> Personnes
            = new List<Personne>
            {
                new Personne { Id = 1, LastName = "Ly", FirstName = "Khun", Age = 38 },
                new Personne { Id = 2, LastName = "Person", FirstName = "Mike", Age = 38 },
            }; 

        public ActionResult ViewWithModel(int id)
        {
            // rechercher un model en db
            Personne model = Personnes.FirstOrDefault(x => x.Id == id);
            // verifier que ce model soit différent de null
            if(model == null)
            {
                //Declencher une erreur 404
                return new HttpNotFoundResult();
            }
            return View(model);
        }

        public ActionResult ViewWithList()
        {
            return View(Personnes);
        }
    }
}

MyFirstASPAPP/Controllers/ReservationController.cs
using MyFirstASPAPP.Models;
using MyFirstASPAPP.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace MyFirstASPAPP.Controllers
{
    public class ReservationController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            // affiche le formulaire
            return View();
        }

        [HttpPost]
        public ActionResult Index(Reservation r)
        {
            // valide le formulaire
            if(ModelState.IsValid)
            {
                // Gmail
                // host = smtp.gmail.com
                // port = 465 ou 587
                // Si Valid => Envoi Email

                SmtpClient c = ServicesLocator.GetMailer();

                string body = $"<h1>Reservation au nom de {r.NomClient}</h1>";
                body += $"<p>Email: {r.EmailClient}</p>";
                body += $"<p>Date: {r.Date.ToShortDateString()}</p>";
                body += $"<p>Heure: {r.Time.ToShortTimeString()}</p>";

                MailMessage m = new MailMessage();
                m.From = new MailAddress("tb.pizzayolo2020@gmail.com");
                m.To.Add("tb.pizzayolo2020@gmail.com");
                m.Body = body;
                m.Subject = "Demande de Réservation";
                m.IsBodyHtml = true;

                c.Send(m);
                return RedirectToAction("Index", "Biere");
            }
            else
            {
                // Si Non valide =>
                // afficher message d'erreur
                ViewBag.Message = "Email n'a pas été envoyé, ...";
                return View(r);
            }
        }
    }
}

MyFirstASPAPP/Views/Biere/Add.cshtml
@model MyFirstASPAPP.Models.Biere
@section title { Créer une nouvelle Biere }
<h1>Créer une nouvelle Biere</h1>
<form action="#" method="post">
    <input type="text" name="Nom" placeholder="Nom de la biere" value="@(Model?.Nom)"/>
    <p class="red">@Html.ValidationMessage("Nom")</p>
    <input type="number" name="Prix" placeholder="Prix de la biere" value="@(Model?.Prix)"/>
    <p class="red">@Html.ValidationMessage("Prix")</p>
    <input type="text" name="Image" placeholder="Url de l'image" value="@(Model?.Image)"/>
    <p class="red">@Html.ValidationMessage("url")</p>
    <button>Save</button>
</form>

MyFirstASPAPP/Views/Biere/Details.cshtml
@model MyFirstASPAPP.Models.Biere
@section title{ Details de la bière @Model.Nom}


<h1>@Model.Nom</h1>
<img src="@Model.Image" style="height:300px;width:auto" />
@if (Model.Prix >= 3)
{
    <p class="red">Prix: @Model.Prix €</p>
}
else
{
    <p class="green">Prix: @Model.Prix €</p>
}
@*<p class="@(Model.Prix >=3 ? "red" : "green")">Prix: @Model.Prix €</p>*@

MyFirstASPAPP/Views/Biere/Index.cshtml
@model IEnumerable<MyFirstASPAPP.Models.Biere>
@section title { Listes de Bières }

    <p>Listes de Bières</p>
    <ul>
        @foreach(var item in Model)
        {
        <li>
            <a href="@Url.Action("Details","Biere", new { id=item.Id })">
                <img style="height:auto;width:100px" src="@item.Image"/>
            </a>
            @*@Html.ActionLink(item.Nom, ....)*@
        </li>
        }
    </ul>

MyFirstASPAPP/Views/Default/Index.cshtml
@section title {
    Ma Super Application - Index
}

@{ 
    int a = 42;
    int b = a + 42;
}

<p>Hello World !! @b</p>

MyFirstASPAPP/Views/Default/ViewWithList.cshtml
@model IEnumerable<MyFirstASPAPP.Models.Personne>

@section title { Liste des Personnes }

<h2>ViewWithList</h2>

<table class="table">
    <tr>
        <th>
            Nom
        </th>
        <th>
            Prenom
        </th>
        <th>
            Age
        </th>
    </tr>
@foreach (var item in Model) {
    
        <tr>
            <td>
                @*<a href="/Default/ViewWithModel/@item.Id">@item.LastName</a>*@
                @Html.ActionLink(item.LastName, "ViewWithModel", "Default", new { id = item.Id }, null)
            </td>
            <td>
                @item.FirstName
            </td>
            <td>
                @item.Age
            </td>
        </tr>
}

</table>

MyFirstASPAPP/Views/Default/ViewWithModel.cshtml
@model MyFirstASPAPP.Models.Personne

@section title{ My First App - Vue avec Model }

<h2>Nom: @Model.LastName</h2>
<p>Prenom: @Model.FirstName</p>
<p>Age: @Model.Age</p>

MyFirstASPAPP/Views/Default/ViewWithVariable.cshtml
@model int
@section title {
    Ma Super App - Test Page
}

<h2>ViewWithVariable @Model</h2>

MyFirstASPAPP/Views/Reservation/Index.cshtml
@model MyFirstASPAPP.Models.Reservation

@section title { Réservation }

<h2>Faites une demande de révervation maintenant</h2>

@if(ViewBag.Message != null)
{
    <p>@ViewBag.Message</p>
}

<form action="#" method="post">
    <input type="text" name="NomClient" value="@(Model?.NomClient)" />
    <p class="red">@Html.ValidationMessage("NomClient")</p>
    @*<p class="red">@Html.ValidationMessageFor(m => m.NomClient)</p>*@
    <input type="email" name="EmailClient" value="@(Model?.EmailClient)" />
    <p class="red">@Html.ValidationMessage("EmailClient")</p>
    <input type="number" name="NbPersonnes" value="@(Model?.NbPersonnes)" />
    <p class="red">@Html.ValidationMessage("NbPersonnes")</p>
    <input type="Date" name="Date" value="@(Model?.Date)" />
    <p class="red">@Html.ValidationMessage("Date")</p>
    <input type="time" name="Time" value="@(Model?.Time)" />
    <p class="red">@Html.ValidationMessage("Time")</p>
    <textarea name="Message">@(Model?.Message)</textarea>
    <p class="red">@Html.ValidationMessage("Message")</p>
    <button>Révervez</button>
</form>

MyFirstASPAPP/Views/Reservation/MailReservationAdmin.cshtml
@model MyFirstASPAPP.Models.Reservation
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MailReservationAdmin</title>
</head>
<body>
    <div>
        <h1>Demande de Réservation au nom de @Model.NomClient</h1>
        <p>Email: @Model.EmailClient</p>
        <p>Date: @Model.Date.ToShortDateString()</p>
        <p>Heure: @Model.Time.ToShortTimeString()</p>
    </div>
</body>
</html>

MyFirstASPAPP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="charset" content="UTF-8" />
    <link rel="stylesheet" href="~/Content/Site.css"/>
    <link href="" rel="stylesheet" />
    <title>@RenderSection("title", false)</title>
</head>
<body>
    <header>Mon Header</header>
    <nav>Bientot ici une super Navbar</nav>
    <main>
        @RenderBody()
    </main>
    <footer>Mon Footer</footer>
</body>
</html>